.intel_syntax noprefix
.section .text
.globl _stub_CloseDriver
_stub_CloseDriver:
  jmp dword ptr [_p_CloseDriver]
.globl _stub_DefDriverProc
_stub_DefDriverProc:
  jmp dword ptr [_p_DefDriverProc]
.globl _stub_DriverCallback
_stub_DriverCallback:
  jmp dword ptr [_p_DriverCallback]
.globl _stub_DrvGetModuleHandle
_stub_DrvGetModuleHandle:
  jmp dword ptr [_p_DrvGetModuleHandle]
.globl _stub_GetDriverModuleHandle
_stub_GetDriverModuleHandle:
  jmp dword ptr [_p_GetDriverModuleHandle]
.globl _stub_NotifyCallbackData
_stub_NotifyCallbackData:
  jmp dword ptr [_p_NotifyCallbackData]
.globl _stub_OpenDriver
_stub_OpenDriver:
  jmp dword ptr [_p_OpenDriver]
.globl _stub_PlaySound
_stub_PlaySound:
  jmp dword ptr [_p_PlaySound]
.globl _stub_PlaySoundA
_stub_PlaySoundA:
  jmp dword ptr [_p_PlaySoundA]
.globl _stub_PlaySoundW
_stub_PlaySoundW:
  jmp dword ptr [_p_PlaySoundW]
.globl _stub_SendDriverMessage
_stub_SendDriverMessage:
  jmp dword ptr [_p_SendDriverMessage]
.globl _stub_WOW32DriverCallback
_stub_WOW32DriverCallback:
  jmp dword ptr [_p_WOW32DriverCallback]
.globl _stub_WOW32ResolveMultiMediaHandle
_stub_WOW32ResolveMultiMediaHandle:
  jmp dword ptr [_p_WOW32ResolveMultiMediaHandle]
.globl _stub_WOWAppExit
_stub_WOWAppExit:
  jmp dword ptr [_p_WOWAppExit]
.globl _stub_aux32Message
_stub_aux32Message:
  jmp dword ptr [_p_aux32Message]
.globl _stub_auxGetDevCapsA
_stub_auxGetDevCapsA:
  jmp dword ptr [_p_auxGetDevCapsA]
.globl _stub_auxGetDevCapsW
_stub_auxGetDevCapsW:
  jmp dword ptr [_p_auxGetDevCapsW]
.globl _stub_auxGetNumDevs
_stub_auxGetNumDevs:
  jmp dword ptr [_p_auxGetNumDevs]
.globl _stub_auxGetVolume
_stub_auxGetVolume:
  jmp dword ptr [_p_auxGetVolume]
.globl _stub_auxOutMessage
_stub_auxOutMessage:
  jmp dword ptr [_p_auxOutMessage]
.globl _stub_auxSetVolume
_stub_auxSetVolume:
  jmp dword ptr [_p_auxSetVolume]
.globl _stub_joy32Message
_stub_joy32Message:
  jmp dword ptr [_p_joy32Message]
.globl _stub_joyConfigChanged
_stub_joyConfigChanged:
  jmp dword ptr [_p_joyConfigChanged]
.globl _stub_joyGetDevCapsA
_stub_joyGetDevCapsA:
  jmp dword ptr [_p_joyGetDevCapsA]
.globl _stub_joyGetDevCapsW
_stub_joyGetDevCapsW:
  jmp dword ptr [_p_joyGetDevCapsW]
.globl _stub_joyGetNumDevs
_stub_joyGetNumDevs:
  jmp dword ptr [_p_joyGetNumDevs]
.globl _stub_joyGetPos
_stub_joyGetPos:
  jmp dword ptr [_p_joyGetPos]
.globl _stub_joyGetPosEx
_stub_joyGetPosEx:
  jmp dword ptr [_p_joyGetPosEx]
.globl _stub_joyGetThreshold
_stub_joyGetThreshold:
  jmp dword ptr [_p_joyGetThreshold]
.globl _stub_joyReleaseCapture
_stub_joyReleaseCapture:
  jmp dword ptr [_p_joyReleaseCapture]
.globl _stub_joySetCapture
_stub_joySetCapture:
  jmp dword ptr [_p_joySetCapture]
.globl _stub_joySetThreshold
_stub_joySetThreshold:
  jmp dword ptr [_p_joySetThreshold]
.globl _stub_mci32Message
_stub_mci32Message:
  jmp dword ptr [_p_mci32Message]
.globl _stub_mciDriverNotify
_stub_mciDriverNotify:
  jmp dword ptr [_p_mciDriverNotify]
.globl _stub_mciDriverYield
_stub_mciDriverYield:
  jmp dword ptr [_p_mciDriverYield]
.globl _stub_mciExecute
_stub_mciExecute:
  jmp dword ptr [_p_mciExecute]
.globl _stub_mciFreeCommandResource
_stub_mciFreeCommandResource:
  jmp dword ptr [_p_mciFreeCommandResource]
.globl _stub_mciGetCreatorTask
_stub_mciGetCreatorTask:
  jmp dword ptr [_p_mciGetCreatorTask]
.globl _stub_mciGetDeviceIDA
_stub_mciGetDeviceIDA:
  jmp dword ptr [_p_mciGetDeviceIDA]
.globl _stub_mciGetDeviceIDFromElementIDA
_stub_mciGetDeviceIDFromElementIDA:
  jmp dword ptr [_p_mciGetDeviceIDFromElementIDA]
.globl _stub_mciGetDeviceIDFromElementIDW
_stub_mciGetDeviceIDFromElementIDW:
  jmp dword ptr [_p_mciGetDeviceIDFromElementIDW]
.globl _stub_mciGetDeviceIDW
_stub_mciGetDeviceIDW:
  jmp dword ptr [_p_mciGetDeviceIDW]
.globl _stub_mciGetDriverData
_stub_mciGetDriverData:
  jmp dword ptr [_p_mciGetDriverData]
.globl _stub_mciGetErrorStringA
_stub_mciGetErrorStringA:
  jmp dword ptr [_p_mciGetErrorStringA]
.globl _stub_mciGetErrorStringW
_stub_mciGetErrorStringW:
  jmp dword ptr [_p_mciGetErrorStringW]
.globl _stub_mciGetYieldProc
_stub_mciGetYieldProc:
  jmp dword ptr [_p_mciGetYieldProc]
.globl _stub_mciLoadCommandResource
_stub_mciLoadCommandResource:
  jmp dword ptr [_p_mciLoadCommandResource]
.globl _stub_mciSendCommandA
_stub_mciSendCommandA:
  jmp dword ptr [_p_mciSendCommandA]
.globl _stub_mciSendCommandW
_stub_mciSendCommandW:
  jmp dword ptr [_p_mciSendCommandW]
.globl _stub_mciSendStringA
_stub_mciSendStringA:
  jmp dword ptr [_p_mciSendStringA]
.globl _stub_mciSendStringW
_stub_mciSendStringW:
  jmp dword ptr [_p_mciSendStringW]
.globl _stub_mciSetDriverData
_stub_mciSetDriverData:
  jmp dword ptr [_p_mciSetDriverData]
.globl _stub_mciSetYieldProc
_stub_mciSetYieldProc:
  jmp dword ptr [_p_mciSetYieldProc]
.globl _stub_mid32Message
_stub_mid32Message:
  jmp dword ptr [_p_mid32Message]
.globl _stub_midiConnect
_stub_midiConnect:
  jmp dword ptr [_p_midiConnect]
.globl _stub_midiDisconnect
_stub_midiDisconnect:
  jmp dword ptr [_p_midiDisconnect]
.globl _stub_midiInAddBuffer
_stub_midiInAddBuffer:
  jmp dword ptr [_p_midiInAddBuffer]
.globl _stub_midiInClose
_stub_midiInClose:
  jmp dword ptr [_p_midiInClose]
.globl _stub_midiInGetDevCapsA
_stub_midiInGetDevCapsA:
  jmp dword ptr [_p_midiInGetDevCapsA]
.globl _stub_midiInGetDevCapsW
_stub_midiInGetDevCapsW:
  jmp dword ptr [_p_midiInGetDevCapsW]
.globl _stub_midiInGetErrorTextA
_stub_midiInGetErrorTextA:
  jmp dword ptr [_p_midiInGetErrorTextA]
.globl _stub_midiInGetErrorTextW
_stub_midiInGetErrorTextW:
  jmp dword ptr [_p_midiInGetErrorTextW]
.globl _stub_midiInGetID
_stub_midiInGetID:
  jmp dword ptr [_p_midiInGetID]
.globl _stub_midiInGetNumDevs
_stub_midiInGetNumDevs:
  jmp dword ptr [_p_midiInGetNumDevs]
.globl _stub_midiInMessage
_stub_midiInMessage:
  jmp dword ptr [_p_midiInMessage]
.globl _stub_midiInOpen
_stub_midiInOpen:
  jmp dword ptr [_p_midiInOpen]
.globl _stub_midiInPrepareHeader
_stub_midiInPrepareHeader:
  jmp dword ptr [_p_midiInPrepareHeader]
.globl _stub_midiInReset
_stub_midiInReset:
  jmp dword ptr [_p_midiInReset]
.globl _stub_midiInStart
_stub_midiInStart:
  jmp dword ptr [_p_midiInStart]
.globl _stub_midiInStop
_stub_midiInStop:
  jmp dword ptr [_p_midiInStop]
.globl _stub_midiInUnprepareHeader
_stub_midiInUnprepareHeader:
  jmp dword ptr [_p_midiInUnprepareHeader]
.globl _stub_midiOutCacheDrumPatches
_stub_midiOutCacheDrumPatches:
  jmp dword ptr [_p_midiOutCacheDrumPatches]
.globl _stub_midiOutCachePatches
_stub_midiOutCachePatches:
  jmp dword ptr [_p_midiOutCachePatches]
.globl _stub_midiOutClose
_stub_midiOutClose:
  jmp dword ptr [_p_midiOutClose]
.globl _stub_midiOutGetDevCapsA
_stub_midiOutGetDevCapsA:
  jmp dword ptr [_p_midiOutGetDevCapsA]
.globl _stub_midiOutGetDevCapsW
_stub_midiOutGetDevCapsW:
  jmp dword ptr [_p_midiOutGetDevCapsW]
.globl _stub_midiOutGetErrorTextA
_stub_midiOutGetErrorTextA:
  jmp dword ptr [_p_midiOutGetErrorTextA]
.globl _stub_midiOutGetErrorTextW
_stub_midiOutGetErrorTextW:
  jmp dword ptr [_p_midiOutGetErrorTextW]
.globl _stub_midiOutGetID
_stub_midiOutGetID:
  jmp dword ptr [_p_midiOutGetID]
.globl _stub_midiOutGetNumDevs
_stub_midiOutGetNumDevs:
  jmp dword ptr [_p_midiOutGetNumDevs]
.globl _stub_midiOutGetVolume
_stub_midiOutGetVolume:
  jmp dword ptr [_p_midiOutGetVolume]
.globl _stub_midiOutLongMsg
_stub_midiOutLongMsg:
  jmp dword ptr [_p_midiOutLongMsg]
.globl _stub_midiOutMessage
_stub_midiOutMessage:
  jmp dword ptr [_p_midiOutMessage]
.globl _stub_midiOutOpen
_stub_midiOutOpen:
  jmp dword ptr [_p_midiOutOpen]
.globl _stub_midiOutPrepareHeader
_stub_midiOutPrepareHeader:
  jmp dword ptr [_p_midiOutPrepareHeader]
.globl _stub_midiOutReset
_stub_midiOutReset:
  jmp dword ptr [_p_midiOutReset]
.globl _stub_midiOutSetVolume
_stub_midiOutSetVolume:
  jmp dword ptr [_p_midiOutSetVolume]
.globl _stub_midiOutShortMsg
_stub_midiOutShortMsg:
  jmp dword ptr [_p_midiOutShortMsg]
.globl _stub_midiOutUnprepareHeader
_stub_midiOutUnprepareHeader:
  jmp dword ptr [_p_midiOutUnprepareHeader]
.globl _stub_midiStreamClose
_stub_midiStreamClose:
  jmp dword ptr [_p_midiStreamClose]
.globl _stub_midiStreamOpen
_stub_midiStreamOpen:
  jmp dword ptr [_p_midiStreamOpen]
.globl _stub_midiStreamOut
_stub_midiStreamOut:
  jmp dword ptr [_p_midiStreamOut]
.globl _stub_midiStreamPause
_stub_midiStreamPause:
  jmp dword ptr [_p_midiStreamPause]
.globl _stub_midiStreamPosition
_stub_midiStreamPosition:
  jmp dword ptr [_p_midiStreamPosition]
.globl _stub_midiStreamProperty
_stub_midiStreamProperty:
  jmp dword ptr [_p_midiStreamProperty]
.globl _stub_midiStreamRestart
_stub_midiStreamRestart:
  jmp dword ptr [_p_midiStreamRestart]
.globl _stub_midiStreamStop
_stub_midiStreamStop:
  jmp dword ptr [_p_midiStreamStop]
.globl _stub_mixerClose
_stub_mixerClose:
  jmp dword ptr [_p_mixerClose]
.globl _stub_mixerGetControlDetailsA
_stub_mixerGetControlDetailsA:
  jmp dword ptr [_p_mixerGetControlDetailsA]
.globl _stub_mixerGetControlDetailsW
_stub_mixerGetControlDetailsW:
  jmp dword ptr [_p_mixerGetControlDetailsW]
.globl _stub_mixerGetDevCapsA
_stub_mixerGetDevCapsA:
  jmp dword ptr [_p_mixerGetDevCapsA]
.globl _stub_mixerGetDevCapsW
_stub_mixerGetDevCapsW:
  jmp dword ptr [_p_mixerGetDevCapsW]
.globl _stub_mixerGetID
_stub_mixerGetID:
  jmp dword ptr [_p_mixerGetID]
.globl _stub_mixerGetLineControlsA
_stub_mixerGetLineControlsA:
  jmp dword ptr [_p_mixerGetLineControlsA]
.globl _stub_mixerGetLineControlsW
_stub_mixerGetLineControlsW:
  jmp dword ptr [_p_mixerGetLineControlsW]
.globl _stub_mixerGetLineInfoA
_stub_mixerGetLineInfoA:
  jmp dword ptr [_p_mixerGetLineInfoA]
.globl _stub_mixerGetLineInfoW
_stub_mixerGetLineInfoW:
  jmp dword ptr [_p_mixerGetLineInfoW]
.globl _stub_mixerGetNumDevs
_stub_mixerGetNumDevs:
  jmp dword ptr [_p_mixerGetNumDevs]
.globl _stub_mixerMessage
_stub_mixerMessage:
  jmp dword ptr [_p_mixerMessage]
.globl _stub_mixerOpen
_stub_mixerOpen:
  jmp dword ptr [_p_mixerOpen]
.globl _stub_mixerSetControlDetails
_stub_mixerSetControlDetails:
  jmp dword ptr [_p_mixerSetControlDetails]
.globl _stub_mmDrvInstall
_stub_mmDrvInstall:
  jmp dword ptr [_p_mmDrvInstall]
.globl _stub_mmGetCurrentTask
_stub_mmGetCurrentTask:
  jmp dword ptr [_p_mmGetCurrentTask]
.globl _stub_mmTaskBlock
_stub_mmTaskBlock:
  jmp dword ptr [_p_mmTaskBlock]
.globl _stub_mmTaskCreate
_stub_mmTaskCreate:
  jmp dword ptr [_p_mmTaskCreate]
.globl _stub_mmTaskSignal
_stub_mmTaskSignal:
  jmp dword ptr [_p_mmTaskSignal]
.globl _stub_mmTaskYield
_stub_mmTaskYield:
  jmp dword ptr [_p_mmTaskYield]
.globl _stub_mmioAdvance
_stub_mmioAdvance:
  jmp dword ptr [_p_mmioAdvance]
.globl _stub_mmioAscend
_stub_mmioAscend:
  jmp dword ptr [_p_mmioAscend]
.globl _stub_mmioClose
_stub_mmioClose:
  jmp dword ptr [_p_mmioClose]
.globl _stub_mmioCreateChunk
_stub_mmioCreateChunk:
  jmp dword ptr [_p_mmioCreateChunk]
.globl _stub_mmioDescend
_stub_mmioDescend:
  jmp dword ptr [_p_mmioDescend]
.globl _stub_mmioFlush
_stub_mmioFlush:
  jmp dword ptr [_p_mmioFlush]
.globl _stub_mmioGetInfo
_stub_mmioGetInfo:
  jmp dword ptr [_p_mmioGetInfo]
.globl _stub_mmioInstallIOProcA
_stub_mmioInstallIOProcA:
  jmp dword ptr [_p_mmioInstallIOProcA]
.globl _stub_mmioInstallIOProcW
_stub_mmioInstallIOProcW:
  jmp dword ptr [_p_mmioInstallIOProcW]
.globl _stub_mmioOpenA
_stub_mmioOpenA:
  jmp dword ptr [_p_mmioOpenA]
.globl _stub_mmioOpenW
_stub_mmioOpenW:
  jmp dword ptr [_p_mmioOpenW]
.globl _stub_mmioRead
_stub_mmioRead:
  jmp dword ptr [_p_mmioRead]
.globl _stub_mmioRenameA
_stub_mmioRenameA:
  jmp dword ptr [_p_mmioRenameA]
.globl _stub_mmioRenameW
_stub_mmioRenameW:
  jmp dword ptr [_p_mmioRenameW]
.globl _stub_mmioSeek
_stub_mmioSeek:
  jmp dword ptr [_p_mmioSeek]
.globl _stub_mmioSendMessage
_stub_mmioSendMessage:
  jmp dword ptr [_p_mmioSendMessage]
.globl _stub_mmioSetBuffer
_stub_mmioSetBuffer:
  jmp dword ptr [_p_mmioSetBuffer]
.globl _stub_mmioSetInfo
_stub_mmioSetInfo:
  jmp dword ptr [_p_mmioSetInfo]
.globl _stub_mmioStringToFOURCCA
_stub_mmioStringToFOURCCA:
  jmp dword ptr [_p_mmioStringToFOURCCA]
.globl _stub_mmioStringToFOURCCW
_stub_mmioStringToFOURCCW:
  jmp dword ptr [_p_mmioStringToFOURCCW]
.globl _stub_mmioWrite
_stub_mmioWrite:
  jmp dword ptr [_p_mmioWrite]
.globl _stub_mmsystemGetVersion
_stub_mmsystemGetVersion:
  jmp dword ptr [_p_mmsystemGetVersion]
.globl _stub_mod32Message
_stub_mod32Message:
  jmp dword ptr [_p_mod32Message]
.globl _stub_mxd32Message
_stub_mxd32Message:
  jmp dword ptr [_p_mxd32Message]
.globl _stub_sndPlaySoundA
_stub_sndPlaySoundA:
  jmp dword ptr [_p_sndPlaySoundA]
.globl _stub_sndPlaySoundW
_stub_sndPlaySoundW:
  jmp dword ptr [_p_sndPlaySoundW]
.globl _stub_tid32Message
_stub_tid32Message:
  jmp dword ptr [_p_tid32Message]
.globl _stub_timeBeginPeriod
_stub_timeBeginPeriod:
  jmp dword ptr [_p_timeBeginPeriod]
.globl _stub_timeEndPeriod
_stub_timeEndPeriod:
  jmp dword ptr [_p_timeEndPeriod]
.globl _stub_timeGetDevCaps
_stub_timeGetDevCaps:
  jmp dword ptr [_p_timeGetDevCaps]
.globl _stub_timeGetSystemTime
_stub_timeGetSystemTime:
  jmp dword ptr [_p_timeGetSystemTime]
.globl _stub_timeGetTime
_stub_timeGetTime:
  jmp dword ptr [_p_timeGetTime]
.globl _stub_timeKillEvent
_stub_timeKillEvent:
  jmp dword ptr [_p_timeKillEvent]
.globl _stub_timeSetEvent
_stub_timeSetEvent:
  jmp dword ptr [_p_timeSetEvent]
.globl _stub_waveInAddBuffer
_stub_waveInAddBuffer:
  jmp dword ptr [_p_waveInAddBuffer]
.globl _stub_waveInClose
_stub_waveInClose:
  jmp dword ptr [_p_waveInClose]
.globl _stub_waveInGetDevCapsA
_stub_waveInGetDevCapsA:
  jmp dword ptr [_p_waveInGetDevCapsA]
.globl _stub_waveInGetDevCapsW
_stub_waveInGetDevCapsW:
  jmp dword ptr [_p_waveInGetDevCapsW]
.globl _stub_waveInGetErrorTextA
_stub_waveInGetErrorTextA:
  jmp dword ptr [_p_waveInGetErrorTextA]
.globl _stub_waveInGetErrorTextW
_stub_waveInGetErrorTextW:
  jmp dword ptr [_p_waveInGetErrorTextW]
.globl _stub_waveInGetID
_stub_waveInGetID:
  jmp dword ptr [_p_waveInGetID]
.globl _stub_waveInGetNumDevs
_stub_waveInGetNumDevs:
  jmp dword ptr [_p_waveInGetNumDevs]
.globl _stub_waveInGetPosition
_stub_waveInGetPosition:
  jmp dword ptr [_p_waveInGetPosition]
.globl _stub_waveInMessage
_stub_waveInMessage:
  jmp dword ptr [_p_waveInMessage]
.globl _stub_waveInOpen
_stub_waveInOpen:
  jmp dword ptr [_p_waveInOpen]
.globl _stub_waveInPrepareHeader
_stub_waveInPrepareHeader:
  jmp dword ptr [_p_waveInPrepareHeader]
.globl _stub_waveInReset
_stub_waveInReset:
  jmp dword ptr [_p_waveInReset]
.globl _stub_waveInStart
_stub_waveInStart:
  jmp dword ptr [_p_waveInStart]
.globl _stub_waveInStop
_stub_waveInStop:
  jmp dword ptr [_p_waveInStop]
.globl _stub_waveInUnprepareHeader
_stub_waveInUnprepareHeader:
  jmp dword ptr [_p_waveInUnprepareHeader]
.globl _stub_waveOutBreakLoop
_stub_waveOutBreakLoop:
  jmp dword ptr [_p_waveOutBreakLoop]
.globl _stub_waveOutClose
_stub_waveOutClose:
  jmp dword ptr [_p_waveOutClose]
.globl _stub_waveOutGetDevCapsA
_stub_waveOutGetDevCapsA:
  jmp dword ptr [_p_waveOutGetDevCapsA]
.globl _stub_waveOutGetDevCapsW
_stub_waveOutGetDevCapsW:
  jmp dword ptr [_p_waveOutGetDevCapsW]
.globl _stub_waveOutGetErrorTextA
_stub_waveOutGetErrorTextA:
  jmp dword ptr [_p_waveOutGetErrorTextA]
.globl _stub_waveOutGetErrorTextW
_stub_waveOutGetErrorTextW:
  jmp dword ptr [_p_waveOutGetErrorTextW]
.globl _stub_waveOutGetID
_stub_waveOutGetID:
  jmp dword ptr [_p_waveOutGetID]
.globl _stub_waveOutGetNumDevs
_stub_waveOutGetNumDevs:
  jmp dword ptr [_p_waveOutGetNumDevs]
.globl _stub_waveOutGetPitch
_stub_waveOutGetPitch:
  jmp dword ptr [_p_waveOutGetPitch]
.globl _stub_waveOutGetPlaybackRate
_stub_waveOutGetPlaybackRate:
  jmp dword ptr [_p_waveOutGetPlaybackRate]
.globl _stub_waveOutGetPosition
_stub_waveOutGetPosition:
  jmp dword ptr [_p_waveOutGetPosition]
.globl _stub_waveOutGetVolume
_stub_waveOutGetVolume:
  jmp dword ptr [_p_waveOutGetVolume]
.globl _stub_waveOutMessage
_stub_waveOutMessage:
  jmp dword ptr [_p_waveOutMessage]
.globl _stub_waveOutOpen
_stub_waveOutOpen:
  jmp dword ptr [_p_waveOutOpen]
.globl _stub_waveOutPause
_stub_waveOutPause:
  jmp dword ptr [_p_waveOutPause]
.globl _stub_waveOutPrepareHeader
_stub_waveOutPrepareHeader:
  jmp dword ptr [_p_waveOutPrepareHeader]
.globl _stub_waveOutReset
_stub_waveOutReset:
  jmp dword ptr [_p_waveOutReset]
.globl _stub_waveOutRestart
_stub_waveOutRestart:
  jmp dword ptr [_p_waveOutRestart]
.globl _stub_waveOutSetPitch
_stub_waveOutSetPitch:
  jmp dword ptr [_p_waveOutSetPitch]
.globl _stub_waveOutSetPlaybackRate
_stub_waveOutSetPlaybackRate:
  jmp dword ptr [_p_waveOutSetPlaybackRate]
.globl _stub_waveOutSetVolume
_stub_waveOutSetVolume:
  jmp dword ptr [_p_waveOutSetVolume]
.globl _stub_waveOutUnprepareHeader
_stub_waveOutUnprepareHeader:
  jmp dword ptr [_p_waveOutUnprepareHeader]
.globl _stub_waveOutWrite
_stub_waveOutWrite:
  jmp dword ptr [_p_waveOutWrite]
.globl _stub_wid32Message
_stub_wid32Message:
  jmp dword ptr [_p_wid32Message]
.globl _stub_winmmDbgOut
_stub_winmmDbgOut:
  jmp dword ptr [_p_winmmDbgOut]
.globl _stub_winmmSetDebugLevel
_stub_winmmSetDebugLevel:
  jmp dword ptr [_p_winmmSetDebugLevel]
.globl _stub_wod32Message
_stub_wod32Message:
  jmp dword ptr [_p_wod32Message]
.section .data
.globl _p_CloseDriver
_p_CloseDriver: .long 0
.globl _p_DefDriverProc
_p_DefDriverProc: .long 0
.globl _p_DriverCallback
_p_DriverCallback: .long 0
.globl _p_DrvGetModuleHandle
_p_DrvGetModuleHandle: .long 0
.globl _p_GetDriverModuleHandle
_p_GetDriverModuleHandle: .long 0
.globl _p_NotifyCallbackData
_p_NotifyCallbackData: .long 0
.globl _p_OpenDriver
_p_OpenDriver: .long 0
.globl _p_PlaySound
_p_PlaySound: .long 0
.globl _p_PlaySoundA
_p_PlaySoundA: .long 0
.globl _p_PlaySoundW
_p_PlaySoundW: .long 0
.globl _p_SendDriverMessage
_p_SendDriverMessage: .long 0
.globl _p_WOW32DriverCallback
_p_WOW32DriverCallback: .long 0
.globl _p_WOW32ResolveMultiMediaHandle
_p_WOW32ResolveMultiMediaHandle: .long 0
.globl _p_WOWAppExit
_p_WOWAppExit: .long 0
.globl _p_aux32Message
_p_aux32Message: .long 0
.globl _p_auxGetDevCapsA
_p_auxGetDevCapsA: .long 0
.globl _p_auxGetDevCapsW
_p_auxGetDevCapsW: .long 0
.globl _p_auxGetNumDevs
_p_auxGetNumDevs: .long 0
.globl _p_auxGetVolume
_p_auxGetVolume: .long 0
.globl _p_auxOutMessage
_p_auxOutMessage: .long 0
.globl _p_auxSetVolume
_p_auxSetVolume: .long 0
.globl _p_joy32Message
_p_joy32Message: .long 0
.globl _p_joyConfigChanged
_p_joyConfigChanged: .long 0
.globl _p_joyGetDevCapsA
_p_joyGetDevCapsA: .long 0
.globl _p_joyGetDevCapsW
_p_joyGetDevCapsW: .long 0
.globl _p_joyGetNumDevs
_p_joyGetNumDevs: .long 0
.globl _p_joyGetPos
_p_joyGetPos: .long 0
.globl _p_joyGetPosEx
_p_joyGetPosEx: .long 0
.globl _p_joyGetThreshold
_p_joyGetThreshold: .long 0
.globl _p_joyReleaseCapture
_p_joyReleaseCapture: .long 0
.globl _p_joySetCapture
_p_joySetCapture: .long 0
.globl _p_joySetThreshold
_p_joySetThreshold: .long 0
.globl _p_mci32Message
_p_mci32Message: .long 0
.globl _p_mciDriverNotify
_p_mciDriverNotify: .long 0
.globl _p_mciDriverYield
_p_mciDriverYield: .long 0
.globl _p_mciExecute
_p_mciExecute: .long 0
.globl _p_mciFreeCommandResource
_p_mciFreeCommandResource: .long 0
.globl _p_mciGetCreatorTask
_p_mciGetCreatorTask: .long 0
.globl _p_mciGetDeviceIDA
_p_mciGetDeviceIDA: .long 0
.globl _p_mciGetDeviceIDFromElementIDA
_p_mciGetDeviceIDFromElementIDA: .long 0
.globl _p_mciGetDeviceIDFromElementIDW
_p_mciGetDeviceIDFromElementIDW: .long 0
.globl _p_mciGetDeviceIDW
_p_mciGetDeviceIDW: .long 0
.globl _p_mciGetDriverData
_p_mciGetDriverData: .long 0
.globl _p_mciGetErrorStringA
_p_mciGetErrorStringA: .long 0
.globl _p_mciGetErrorStringW
_p_mciGetErrorStringW: .long 0
.globl _p_mciGetYieldProc
_p_mciGetYieldProc: .long 0
.globl _p_mciLoadCommandResource
_p_mciLoadCommandResource: .long 0
.globl _p_mciSendCommandA
_p_mciSendCommandA: .long 0
.globl _p_mciSendCommandW
_p_mciSendCommandW: .long 0
.globl _p_mciSendStringA
_p_mciSendStringA: .long 0
.globl _p_mciSendStringW
_p_mciSendStringW: .long 0
.globl _p_mciSetDriverData
_p_mciSetDriverData: .long 0
.globl _p_mciSetYieldProc
_p_mciSetYieldProc: .long 0
.globl _p_mid32Message
_p_mid32Message: .long 0
.globl _p_midiConnect
_p_midiConnect: .long 0
.globl _p_midiDisconnect
_p_midiDisconnect: .long 0
.globl _p_midiInAddBuffer
_p_midiInAddBuffer: .long 0
.globl _p_midiInClose
_p_midiInClose: .long 0
.globl _p_midiInGetDevCapsA
_p_midiInGetDevCapsA: .long 0
.globl _p_midiInGetDevCapsW
_p_midiInGetDevCapsW: .long 0
.globl _p_midiInGetErrorTextA
_p_midiInGetErrorTextA: .long 0
.globl _p_midiInGetErrorTextW
_p_midiInGetErrorTextW: .long 0
.globl _p_midiInGetID
_p_midiInGetID: .long 0
.globl _p_midiInGetNumDevs
_p_midiInGetNumDevs: .long 0
.globl _p_midiInMessage
_p_midiInMessage: .long 0
.globl _p_midiInOpen
_p_midiInOpen: .long 0
.globl _p_midiInPrepareHeader
_p_midiInPrepareHeader: .long 0
.globl _p_midiInReset
_p_midiInReset: .long 0
.globl _p_midiInStart
_p_midiInStart: .long 0
.globl _p_midiInStop
_p_midiInStop: .long 0
.globl _p_midiInUnprepareHeader
_p_midiInUnprepareHeader: .long 0
.globl _p_midiOutCacheDrumPatches
_p_midiOutCacheDrumPatches: .long 0
.globl _p_midiOutCachePatches
_p_midiOutCachePatches: .long 0
.globl _p_midiOutClose
_p_midiOutClose: .long 0
.globl _p_midiOutGetDevCapsA
_p_midiOutGetDevCapsA: .long 0
.globl _p_midiOutGetDevCapsW
_p_midiOutGetDevCapsW: .long 0
.globl _p_midiOutGetErrorTextA
_p_midiOutGetErrorTextA: .long 0
.globl _p_midiOutGetErrorTextW
_p_midiOutGetErrorTextW: .long 0
.globl _p_midiOutGetID
_p_midiOutGetID: .long 0
.globl _p_midiOutGetNumDevs
_p_midiOutGetNumDevs: .long 0
.globl _p_midiOutGetVolume
_p_midiOutGetVolume: .long 0
.globl _p_midiOutLongMsg
_p_midiOutLongMsg: .long 0
.globl _p_midiOutMessage
_p_midiOutMessage: .long 0
.globl _p_midiOutOpen
_p_midiOutOpen: .long 0
.globl _p_midiOutPrepareHeader
_p_midiOutPrepareHeader: .long 0
.globl _p_midiOutReset
_p_midiOutReset: .long 0
.globl _p_midiOutSetVolume
_p_midiOutSetVolume: .long 0
.globl _p_midiOutShortMsg
_p_midiOutShortMsg: .long 0
.globl _p_midiOutUnprepareHeader
_p_midiOutUnprepareHeader: .long 0
.globl _p_midiStreamClose
_p_midiStreamClose: .long 0
.globl _p_midiStreamOpen
_p_midiStreamOpen: .long 0
.globl _p_midiStreamOut
_p_midiStreamOut: .long 0
.globl _p_midiStreamPause
_p_midiStreamPause: .long 0
.globl _p_midiStreamPosition
_p_midiStreamPosition: .long 0
.globl _p_midiStreamProperty
_p_midiStreamProperty: .long 0
.globl _p_midiStreamRestart
_p_midiStreamRestart: .long 0
.globl _p_midiStreamStop
_p_midiStreamStop: .long 0
.globl _p_mixerClose
_p_mixerClose: .long 0
.globl _p_mixerGetControlDetailsA
_p_mixerGetControlDetailsA: .long 0
.globl _p_mixerGetControlDetailsW
_p_mixerGetControlDetailsW: .long 0
.globl _p_mixerGetDevCapsA
_p_mixerGetDevCapsA: .long 0
.globl _p_mixerGetDevCapsW
_p_mixerGetDevCapsW: .long 0
.globl _p_mixerGetID
_p_mixerGetID: .long 0
.globl _p_mixerGetLineControlsA
_p_mixerGetLineControlsA: .long 0
.globl _p_mixerGetLineControlsW
_p_mixerGetLineControlsW: .long 0
.globl _p_mixerGetLineInfoA
_p_mixerGetLineInfoA: .long 0
.globl _p_mixerGetLineInfoW
_p_mixerGetLineInfoW: .long 0
.globl _p_mixerGetNumDevs
_p_mixerGetNumDevs: .long 0
.globl _p_mixerMessage
_p_mixerMessage: .long 0
.globl _p_mixerOpen
_p_mixerOpen: .long 0
.globl _p_mixerSetControlDetails
_p_mixerSetControlDetails: .long 0
.globl _p_mmDrvInstall
_p_mmDrvInstall: .long 0
.globl _p_mmGetCurrentTask
_p_mmGetCurrentTask: .long 0
.globl _p_mmTaskBlock
_p_mmTaskBlock: .long 0
.globl _p_mmTaskCreate
_p_mmTaskCreate: .long 0
.globl _p_mmTaskSignal
_p_mmTaskSignal: .long 0
.globl _p_mmTaskYield
_p_mmTaskYield: .long 0
.globl _p_mmioAdvance
_p_mmioAdvance: .long 0
.globl _p_mmioAscend
_p_mmioAscend: .long 0
.globl _p_mmioClose
_p_mmioClose: .long 0
.globl _p_mmioCreateChunk
_p_mmioCreateChunk: .long 0
.globl _p_mmioDescend
_p_mmioDescend: .long 0
.globl _p_mmioFlush
_p_mmioFlush: .long 0
.globl _p_mmioGetInfo
_p_mmioGetInfo: .long 0
.globl _p_mmioInstallIOProcA
_p_mmioInstallIOProcA: .long 0
.globl _p_mmioInstallIOProcW
_p_mmioInstallIOProcW: .long 0
.globl _p_mmioOpenA
_p_mmioOpenA: .long 0
.globl _p_mmioOpenW
_p_mmioOpenW: .long 0
.globl _p_mmioRead
_p_mmioRead: .long 0
.globl _p_mmioRenameA
_p_mmioRenameA: .long 0
.globl _p_mmioRenameW
_p_mmioRenameW: .long 0
.globl _p_mmioSeek
_p_mmioSeek: .long 0
.globl _p_mmioSendMessage
_p_mmioSendMessage: .long 0
.globl _p_mmioSetBuffer
_p_mmioSetBuffer: .long 0
.globl _p_mmioSetInfo
_p_mmioSetInfo: .long 0
.globl _p_mmioStringToFOURCCA
_p_mmioStringToFOURCCA: .long 0
.globl _p_mmioStringToFOURCCW
_p_mmioStringToFOURCCW: .long 0
.globl _p_mmioWrite
_p_mmioWrite: .long 0
.globl _p_mmsystemGetVersion
_p_mmsystemGetVersion: .long 0
.globl _p_mod32Message
_p_mod32Message: .long 0
.globl _p_mxd32Message
_p_mxd32Message: .long 0
.globl _p_sndPlaySoundA
_p_sndPlaySoundA: .long 0
.globl _p_sndPlaySoundW
_p_sndPlaySoundW: .long 0
.globl _p_tid32Message
_p_tid32Message: .long 0
.globl _p_timeBeginPeriod
_p_timeBeginPeriod: .long 0
.globl _p_timeEndPeriod
_p_timeEndPeriod: .long 0
.globl _p_timeGetDevCaps
_p_timeGetDevCaps: .long 0
.globl _p_timeGetSystemTime
_p_timeGetSystemTime: .long 0
.globl _p_timeGetTime
_p_timeGetTime: .long 0
.globl _p_timeKillEvent
_p_timeKillEvent: .long 0
.globl _p_timeSetEvent
_p_timeSetEvent: .long 0
.globl _p_waveInAddBuffer
_p_waveInAddBuffer: .long 0
.globl _p_waveInClose
_p_waveInClose: .long 0
.globl _p_waveInGetDevCapsA
_p_waveInGetDevCapsA: .long 0
.globl _p_waveInGetDevCapsW
_p_waveInGetDevCapsW: .long 0
.globl _p_waveInGetErrorTextA
_p_waveInGetErrorTextA: .long 0
.globl _p_waveInGetErrorTextW
_p_waveInGetErrorTextW: .long 0
.globl _p_waveInGetID
_p_waveInGetID: .long 0
.globl _p_waveInGetNumDevs
_p_waveInGetNumDevs: .long 0
.globl _p_waveInGetPosition
_p_waveInGetPosition: .long 0
.globl _p_waveInMessage
_p_waveInMessage: .long 0
.globl _p_waveInOpen
_p_waveInOpen: .long 0
.globl _p_waveInPrepareHeader
_p_waveInPrepareHeader: .long 0
.globl _p_waveInReset
_p_waveInReset: .long 0
.globl _p_waveInStart
_p_waveInStart: .long 0
.globl _p_waveInStop
_p_waveInStop: .long 0
.globl _p_waveInUnprepareHeader
_p_waveInUnprepareHeader: .long 0
.globl _p_waveOutBreakLoop
_p_waveOutBreakLoop: .long 0
.globl _p_waveOutClose
_p_waveOutClose: .long 0
.globl _p_waveOutGetDevCapsA
_p_waveOutGetDevCapsA: .long 0
.globl _p_waveOutGetDevCapsW
_p_waveOutGetDevCapsW: .long 0
.globl _p_waveOutGetErrorTextA
_p_waveOutGetErrorTextA: .long 0
.globl _p_waveOutGetErrorTextW
_p_waveOutGetErrorTextW: .long 0
.globl _p_waveOutGetID
_p_waveOutGetID: .long 0
.globl _p_waveOutGetNumDevs
_p_waveOutGetNumDevs: .long 0
.globl _p_waveOutGetPitch
_p_waveOutGetPitch: .long 0
.globl _p_waveOutGetPlaybackRate
_p_waveOutGetPlaybackRate: .long 0
.globl _p_waveOutGetPosition
_p_waveOutGetPosition: .long 0
.globl _p_waveOutGetVolume
_p_waveOutGetVolume: .long 0
.globl _p_waveOutMessage
_p_waveOutMessage: .long 0
.globl _p_waveOutOpen
_p_waveOutOpen: .long 0
.globl _p_waveOutPause
_p_waveOutPause: .long 0
.globl _p_waveOutPrepareHeader
_p_waveOutPrepareHeader: .long 0
.globl _p_waveOutReset
_p_waveOutReset: .long 0
.globl _p_waveOutRestart
_p_waveOutRestart: .long 0
.globl _p_waveOutSetPitch
_p_waveOutSetPitch: .long 0
.globl _p_waveOutSetPlaybackRate
_p_waveOutSetPlaybackRate: .long 0
.globl _p_waveOutSetVolume
_p_waveOutSetVolume: .long 0
.globl _p_waveOutUnprepareHeader
_p_waveOutUnprepareHeader: .long 0
.globl _p_waveOutWrite
_p_waveOutWrite: .long 0
.globl _p_wid32Message
_p_wid32Message: .long 0
.globl _p_winmmDbgOut
_p_winmmDbgOut: .long 0
.globl _p_winmmSetDebugLevel
_p_winmmSetDebugLevel: .long 0
.globl _p_wod32Message
_p_wod32Message: .long 0
